services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:ng
    container_name: nginx
    ports: ['${EXPOSED_PORT}:${EXPOSED_PORT}']
    restart: on-failure
    env_file: ./.env
    environment: [URL EXPOSED_PORT]
    volumes: ['wp_file_volume:/app/data/']
    networks: [nginx_wp]
    depends_on:
      wordpress:
        condition: service_healthy
        restart: true
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:wp
    container_name: wordpress
    restart: on-failure
    env_file: ./.env
    secrets:
      - db_pass
      - credentials
      - credentials2
    environment: [ADMIN_NAME USER_NAME DB_NAME URL TITLE EXPOSED_PORT DB_PORT WP_PORT]
    volumes: ['wp_file_volume:/app/data/']
    networks: [nginx_wp, wp_mariadb]
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "pidof", "php-fpm83"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:mb
    container_name: mariadb
    restart: on-failure
    env_file: ./.env
    secrets:
      - db_pass
      - db_root_pass
      - credentials
      - credentials2
    environment: [ADMIN_NAME USER_NAME URL EXPOSED_PORT DB_PORT]
    volumes: ['wp_db_volume:/app/data/']
    networks: [wp_mariadb]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
volumes:
  wp_file_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER_HOME}/data/wordpress
  wp_db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER_HOME}/data/mariadb
networks:
  nginx_wp:
  wp_mariadb:
secrets:
  credentials:
    file: ../secrets/credentials.txt
  credentials2:
    file: ../secrets/credentials2.txt
  db_pass:
    file: ../secrets/db_password.txt
  db_root_pass:
    file: ../secrets/db_root_password.txt
