---
version: '3.8'
services:
  nginx:
    build:
      context: mariadb
      dockerfile: Dockerfile
    ports: [443:443]
    restart: on-failure
    networks:
      nginxNetworks:
        ipv4_address: ip
