version: '3.8'

services:
  nginx:
    image: nginx
    ports:
    "443:443"
    restart: always
    networks:
      nginxNetworks:
        ipv4_address: ip
  wordpress:
    image: wordpress
    ports:
      "8080:80"
    depends_on:
      mysql #this should be created first
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "small"
      WORDPRESS_DB_NAME: wordpress
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "small"
    volumes:
      ./mysql:/var/lib/mysql
networks:
  nginxNetworks:
    ipam: #ip address management
      driver: default
      config:
        subnet: 
